Description: CD12352 - Infrastructure as Code Project - Udagram

Parameters:
  # Add your parameters here
  EnvironmentName:
    Type: String
    Description: An environment name that will be prefixed to resource names
    Default: dev
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: must be dev or prod

Resources:
  # Add your resources here
  UdagramIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvironmentName}-Udagram-Role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub "${EnvironmentName}-Udagram-Policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DescribeInstances
                  - ec2:AssociateAddress
                  - ec2:AllocateAddress
                  - ec2:DescribeAddresses
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:Get*
                  - s3:Put*
                Resource:
                  - !Sub "arn:aws:s3:::dev-udagram-prj-2"

  UdagaramInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref UdagramIAMRole

Outputs:
  # Add your outputs here
  UdagramIAMRole:
    Description: Udagram IAM Role
    Value: !Ref UdagramIAMRole
    Export:
      Name: !Sub "${EnvironmentName}-Udagram-IAM-Role"

  UdagaramInstanceProfile:
    Description: Udagram Instance Profile
    Value: !Ref UdagaramInstanceProfile
    Export:
      Name: !Sub "${EnvironmentName}-Udagram-Instance-Profile"
